# Make sure the service is started, and restart if necessary
- name: Start elasticsearch service
  service: name={{es_service_name}} state=started enabled=yes
  when: es_start_service
  register: elasticsearch_started

